title: APTL Documentation
description: AI Prompt Template Language - A modern template engine for authoring AI system prompts
url: https://finqu.github.io
baseurl: /aptl
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
plugins:
  - jekyll-seo-tag

# Exclude remote theme to use custom layout
theme: null
remote_theme: null

# Navigation with dropdown groups
navigation:
  - title: Home
    url: /
  - title: Documentation
    dropdown:
      - title: Getting Started
        url: /getting-started
      - title: Syntax Reference
        url: /syntax-reference
      - title: Directives
        url: /directives
      - title: Advanced Features
        url: /advanced-features
  - title: Resources
    dropdown:
      - title: Examples
        url: /examples
      - title: API Reference
        url: /api-reference
      - title: Best Practices
        url: /best-practices

# GitHub metadata
repository: finqu/aptl
