title: APTL Documentation
description: AI Prompt Template Language - A modern template engine for authoring AI system prompts
theme: jekyll-theme-cayman
url: https://finqu.github.io
baseurl: /aptl
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Navigation
navigation:
  - title: Home
    url: /
  - title: Getting Started
    url: /getting-started
  - title: Syntax Reference
    url: /syntax-reference
  - title: Directives
    url: /directives
  - title: Advanced Features
    url: /advanced-features
  - title: Examples
    url: /examples
  - title: API Reference
    url: /api-reference
  - title: Best Practices
    url: /best-practices

# GitHub metadata
repository: finqu/aptl
